services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/workspace         # Mapeia a raiz inteira para o contentor
      - ./database:/database #Temporário
    working_dir: /workspace
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  ingestion:
    build:
      context: .
      dockerfile: ingestion/dockerfile
    env_file:
      - .env
    volumes:
      - ./ingestion:/app
      - ./database:/database #Temporário
    command: python pipeline.py