services:
  api:
    build:
      context: .
      dockerfile: app/dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  ingestion:
    build:
      context: .
      dockerfile: ingestion/dockerfile
    env_file:
      - .env
    volumes:
      - ./ingestion:/app
    command: python pipeline.py